# Build VirtoCommerce.Module.Installer.vsix template and upload it to workflow run artifacs

name: Build VSIX

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@master
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build extension
      run: msbuild ./CSharp/VirtoCommerce.Module.sln /t:Rebuild /p:Configuration=Release

    - uses: actions/upload-artifact@v2
      with:
        name: module-installer
        path: ./CSharp/VirtoCommerce.Module.Installer/bin/Release/VirtoCommerce.Module.Installer.vsix
    
